### ISSUE TITLE
account.nintendo.net does not connect

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [superwhiskers/mitmproxy-nintendo#1]
Hi there.

When i try to use the proxy, the console can't connect to account.nintendo.net due to the following error:

`Client TLS handshake failed. The client does not trust the proxy's certificate for account.nintendo.net (tlsv1 alert unknown ca)`

Any idea how to fix?

**Comment by superwhiskers** [comment]
i apologize for the delay in responding. it appears mitmproxy has been updated to where the previous configuration settings don't work anymore. i've updated the configuration to reflect this, and it works on my end. let me know if it works for you

**Comment by superwhiskers** [comment]
i'll assume this worked / you don't have a use for this tool anymore. if this isn't the case, feel free to reopen this issue.
